dist: xenial
language: python
python: 3.7

env:
  global:
    - SIGNAL_JSON="https://updates.signal.org/android/latest.json"
    - CACHE="$HOME/cache"

cache:
  directories:
    - $HOME/cache

services:
  - docker

before_install:
  - travis_retry wget -P "$CACHE" -N -- "$SIGNAL_JSON"
  - SIGNAL_APK=$(python -c "import json; print(json.loads('$(cat "$CACHE/$(basename -- "$SIGNAL_JSON")")')['url'])") && travis_retry wget -P "$CACHE" -N -- "$SIGNAL_APK" && ln -f "$CACHE/$(basename -- "$SIGNAL_APK")" $HOME/Signal.apk

install:
  - sudo apt-get update -q
  - sudo apt-get install -y aapt adb

script: travis_wait pytest -x test
