dist: xenial
language: python
python: 3.7

services:
  - docker

install:
  - sudo apt-get update -q
  - sudo apt-get install -y aapt adb
  - git clone https://github.com/NoMore201/googleplay-api.git
  - pip install googleplay-api

script: travis_wait 40 pytest -x test
