name: Nightly Build Check

on:
  schedule:
    - cron: '0 5 * * *'
 
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y aapt adb protobuf-compiler
          pip install pytest requests
      - name: Run tests
        run: pytest -x test
